import { StylesProvider } from './styles-provider'
import './globals.css'
import { Provider } from 'app/provider'

export const metadata = {
  title: 'Create Solito App',
  description: 'Generated by create Solito app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className="flex flex-col items-stretch">
        <StylesProvider>
          <Provider>{children}</Provider>
        </StylesProvider>
      </body>
    </html>
  )
}
